services:
  finan.api:
    image: ${DOCKER_REGISTRY-}finanapi
    build:
      context: .
      dockerfile: Finan.Api/Dockerfile
    ports:
      - "5000:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8081
    networks:
      - backend
  finan.web:
    image: ${DOCKER_REGISTRY-}finanweb
    build:
      context: .
      dockerfile: Finan.Web/Dockerfile
    ports:
      - "5000:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8081
    networks:
      - backend
networks:
  backend:
    driver: bridge
