// <auto-generated />
using System;
using Finan.Domain.Enums;
using Finan.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finan.Infra.Data.Migrations
{
    [DbContext(typeof(BaseContext))]
    [Migration("20251015181900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Finan.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Agency");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Balance");

                    b.Property<int>("BankId")
                        .HasColumnType("int")
                        .HasColumnName("BankId");

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("ContractId");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CreditLimit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Number");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("Code");

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("ContractId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Bank", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "001",
                            ContractId = 0,
                            Name = "Banco do Brasil S.A."
                        },
                        new
                        {
                            Id = 2,
                            Code = "033",
                            ContractId = 0,
                            Name = "Banco Santander (Brasil) S.A."
                        },
                        new
                        {
                            Id = 3,
                            Code = "104",
                            ContractId = 0,
                            Name = "Caixa Econômica Federal"
                        },
                        new
                        {
                            Id = 4,
                            Code = "237",
                            ContractId = 0,
                            Name = "Banco Bradesco S.A."
                        },
                        new
                        {
                            Id = 5,
                            Code = "341",
                            ContractId = 0,
                            Name = "Itaú Unibanco S.A."
                        },
                        new
                        {
                            Id = 6,
                            Code = "260",
                            ContractId = 0,
                            Name = "Nu Pagamentos S.A."
                        },
                        new
                        {
                            Id = 7,
                            Code = "336",
                            ContractId = 0,
                            Name = "Banco C6 S.A."
                        },
                        new
                        {
                            Id = 8,
                            Code = "077",
                            ContractId = 0,
                            Name = "Banco Inter S.A."
                        });
                });

            modelBuilder.Entity("Finan.Domain.Entities.BankTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountInId")
                        .HasColumnType("int")
                        .HasColumnName("AccountInId");

                    b.Property<int>("AccountOutId")
                        .HasColumnType("int")
                        .HasColumnName("AccountOutId");

                    b.Property<DateTime>("AccrualPeriodDate")
                        .HasColumnType("datetime")
                        .HasColumnName("AccrualPeriodDate");

                    b.Property<int?>("ClassificationId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("ClassificationId");

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("ContractId");

                    b.Property<int>("CostCenterId")
                        .HasColumnType("int")
                        .HasColumnName("CostCenterId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<int?>("GroupId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("GroupId");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Observation");

                    b.Property<BankTransactionType>("Type")
                        .HasColumnType("tinyint")
                        .HasColumnName("Type");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("GroupId");

                    b.ToTable("BankTransaction", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("ContractId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Classification", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractId = 0,
                            Description = "Moradia",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContractId = 0,
                            Description = "Alimentação",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 3,
                            ContractId = 0,
                            Description = "Transporte",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 4,
                            ContractId = 0,
                            Description = "Lazer",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 5,
                            ContractId = 0,
                            Description = "Viagens",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 6,
                            ContractId = 0,
                            Description = "Salário",
                            GroupId = 3
                        },
                        new
                        {
                            Id = 7,
                            ContractId = 0,
                            Description = "Gratificações e Bônus",
                            GroupId = 3
                        },
                        new
                        {
                            Id = 8,
                            ContractId = 0,
                            Description = "Rendimentos de Poupança",
                            GroupId = 4
                        },
                        new
                        {
                            Id = 9,
                            ContractId = 0,
                            Description = "Dividendos",
                            GroupId = 4
                        },
                        new
                        {
                            Id = 10,
                            ContractId = 0,
                            Description = "Juros de Investimentos",
                            GroupId = 4
                        },
                        new
                        {
                            Id = 11,
                            ContractId = 0,
                            Description = "Aluguel de Imóveis",
                            GroupId = 4
                        },
                        new
                        {
                            Id = 12,
                            ContractId = 0,
                            Description = "Presentes",
                            GroupId = 5
                        },
                        new
                        {
                            Id = 13,
                            ContractId = 0,
                            Description = "Vendas de Bens",
                            GroupId = 5
                        },
                        new
                        {
                            Id = 14,
                            ContractId = 0,
                            Description = "Educação e Cursos",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 15,
                            ContractId = 0,
                            Description = "Cartão de Crédito",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 16,
                            ContractId = 0,
                            Description = "Serviços de Internet, Gás e Energia",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 17,
                            ContractId = 0,
                            Description = "Pagamento de Impostos",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 18,
                            ContractId = 0,
                            Description = "Restituição de Impostos",
                            GroupId = 5
                        });
                });

            modelBuilder.Entity("Finan.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int")
                        .HasColumnName("SubscriptionPlanId");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("Contract", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2124, 10, 15, 15, 18, 59, 970, DateTimeKind.Local).AddTicks(3291),
                            IsActive = true,
                            StartDate = new DateTime(2025, 10, 15, 15, 18, 59, 970, DateTimeKind.Local).AddTicks(3278),
                            SubscriptionPlanId = 1
                        });
                });

            modelBuilder.Entity("Finan.Domain.Entities.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("ContractId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.HasKey("Id");

                    b.ToTable("CostCenter", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractId = 0,
                            Description = "Casa"
                        },
                        new
                        {
                            Id = 2,
                            ContractId = 0,
                            Description = "Transporte"
                        },
                        new
                        {
                            Id = 3,
                            ContractId = 0,
                            Description = "Saúde"
                        },
                        new
                        {
                            Id = 4,
                            ContractId = 0,
                            Description = "Educação"
                        },
                        new
                        {
                            Id = 5,
                            ContractId = 0,
                            Description = "Lazer"
                        },
                        new
                        {
                            Id = 6,
                            ContractId = 0,
                            Description = "Investimentos"
                        },
                        new
                        {
                            Id = 7,
                            ContractId = 0,
                            Description = "Alimentação"
                        },
                        new
                        {
                            Id = 8,
                            ContractId = 0,
                            Description = "Cartão de Crédito"
                        },
                        new
                        {
                            Id = 9,
                            ContractId = 0,
                            Description = "Doações e Presentes"
                        },
                        new
                        {
                            Id = 10,
                            ContractId = 0,
                            Description = "Trabalho Formal"
                        },
                        new
                        {
                            Id = 11,
                            ContractId = 0,
                            Description = "Trabalho Autônomo"
                        },
                        new
                        {
                            Id = 12,
                            ContractId = 0,
                            Description = "Aluguéis"
                        },
                        new
                        {
                            Id = 13,
                            ContractId = 0,
                            Description = "Outras Receitas"
                        });
                });

            modelBuilder.Entity("Finan.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Code");

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("ContractId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("Symbol");

                    b.HasKey("Id");

                    b.ToTable("Currency", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BRL",
                            ContractId = 0,
                            Name = "Real",
                            Symbol = "R$"
                        },
                        new
                        {
                            Id = 2,
                            Code = "USD",
                            ContractId = 0,
                            Name = "Dólar",
                            Symbol = "$"
                        });
                });

            modelBuilder.Entity("Finan.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("ContractId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<NatureGroup>("Nature")
                        .HasColumnType("tinyint")
                        .HasColumnName("Nature");

                    b.HasKey("Id");

                    b.ToTable("Group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractId = 0,
                            Description = "Despesas Fixas",
                            Nature = (byte)0
                        },
                        new
                        {
                            Id = 2,
                            ContractId = 0,
                            Description = "Despesas Variáveis",
                            Nature = (byte)0
                        },
                        new
                        {
                            Id = 3,
                            ContractId = 0,
                            Description = "Receitas de Trabalho",
                            Nature = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            ContractId = 0,
                            Description = "Receitas de Investimentos",
                            Nature = (byte)1
                        },
                        new
                        {
                            Id = 5,
                            ContractId = 0,
                            Description = "Receitas Eventuais ou Extraordinárias",
                            Nature = (byte)1
                        });
                });

            modelBuilder.Entity("Finan.Domain.Entities.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Balance");

                    b.Property<int?>("BankTransactionId")
                        .HasColumnType("int")
                        .HasColumnName("BankTransactionId");

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("ContractId");

                    b.Property<DateTime>("FlowDate")
                        .HasColumnType("datetime")
                        .HasColumnName("FlowDate");

                    b.Property<DateTime?>("ReconciledDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ReconciledDate");

                    b.Property<bool>("Reversed")
                        .HasColumnType("bit")
                        .HasColumnName("Reversed");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("TransactionId");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BankTransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Statement", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("UserQuantity")
                        .HasColumnType("int")
                        .HasColumnName("UserQuantity");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlan", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gratuito",
                            UserQuantity = 1,
                            Value = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Profissional",
                            UserQuantity = 5,
                            Value = 29.90m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Empresarial",
                            UserQuantity = 20,
                            Value = 99.90m
                        });
                });

            modelBuilder.Entity("Finan.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccrualPeriodDate")
                        .HasColumnType("datetime")
                        .HasColumnName("AccrualPeriodDate");

                    b.Property<DateTime>("CashFlowDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CashFlowDate");

                    b.Property<int>("ClassificationId")
                        .HasColumnType("int")
                        .HasColumnName("ClassificationId");

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("ContractId");

                    b.Property<int>("CostCenterId")
                        .HasColumnType("int")
                        .HasColumnName("CostCenterId");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Description");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Discount");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DueDate");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupId");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("IssueDate");

                    b.Property<decimal>("LateFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LateFee");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Observation");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("Status");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalPaid");

                    b.Property<TransactionType>("Type")
                        .HasColumnType("tinyint")
                        .HasColumnName("Type");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("GroupId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("ContractId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractId = 1,
                            Email = "dev.fabianorocha@gmail.com",
                            Password = "Finan@1234",
                            Role = "Manager",
                            UserName = "Finan"
                        });
                });

            modelBuilder.Entity("Finan.Domain.Entities.Account", b =>
                {
                    b.HasOne("Finan.Domain.Entities.Bank", "Bank")
                        .WithMany("Accounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Finan.Domain.Entities.BankTransaction", b =>
                {
                    b.HasOne("Finan.Domain.Entities.Classification", "Classification")
                        .WithMany("BankTransactions")
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany("BankTransactions")
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.Group", "Group")
                        .WithMany("BankTransactions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classification");

                    b.Navigation("CostCenter");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Classification", b =>
                {
                    b.HasOne("Finan.Domain.Entities.Group", "Group")
                        .WithMany("Classifications")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Finan.Domain.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Contracts")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Statement", b =>
                {
                    b.HasOne("Finan.Domain.Entities.Account", "Account")
                        .WithMany("Statements")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.BankTransaction", "BankTransaction")
                        .WithMany("Statements")
                        .HasForeignKey("BankTransactionId");

                    b.HasOne("Finan.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Statements")
                        .HasForeignKey("TransactionId");

                    b.Navigation("Account");

                    b.Navigation("BankTransaction");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Finan.Domain.Entities.Classification", "Classification")
                        .WithMany("Transactions")
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany("Transactions")
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.Currency", "Currency")
                        .WithMany("Transactions")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.Group", "Group")
                        .WithMany("Transactions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classification");

                    b.Navigation("CostCenter");

                    b.Navigation("Currency");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Finan.Domain.Entities.User", b =>
                {
                    b.HasOne("Finan.Domain.Entities.Contract", "Contract")
                        .WithMany("Users")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Account", b =>
                {
                    b.Navigation("Statements");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Bank", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Finan.Domain.Entities.BankTransaction", b =>
                {
                    b.Navigation("Statements");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Classification", b =>
                {
                    b.Navigation("BankTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Finan.Domain.Entities.CostCenter", b =>
                {
                    b.Navigation("BankTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Currency", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Group", b =>
                {
                    b.Navigation("BankTransactions");

                    b.Navigation("Classifications");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finan.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Statements");
                });
#pragma warning restore 612, 618
        }
    }
}
