// <auto-generated />
using System;
using Finan.Domain.Enums;
using Finan.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finan.Infra.Data.Migrations
{
    [DbContext(typeof(BaseContext))]
    [Migration("20260502032658_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finan.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Agency");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Balance");

                    b.Property<int>("BankId")
                        .HasColumnType("integer")
                        .HasColumnName("BankId");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("CreditLimit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Bank", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.BankTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountInId")
                        .HasColumnType("integer")
                        .HasColumnName("AccountInId");

                    b.Property<int>("AccountOutId")
                        .HasColumnType("integer")
                        .HasColumnName("AccountOutId");

                    b.Property<DateTime>("AccrualPeriodDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("AccrualPeriodDate");

                    b.Property<int?>("ClassificationId")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("ClassificationId");

                    b.Property<int>("CostCenterId")
                        .HasColumnType("integer")
                        .HasColumnName("CostCenterId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp")
                        .HasColumnName("Date");

                    b.Property<int?>("GroupId")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("GroupId");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Observation");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<BankTransactionType>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("Type");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("GroupId");

                    b.ToTable("BankTransaction", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("GroupId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Classification", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CostCenter", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Symbol");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Currency", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<NatureGroup>("Nature")
                        .HasColumnType("smallint")
                        .HasColumnName("Nature");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("AccountId");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Balance");

                    b.Property<int?>("BankTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("BankTransactionId");

                    b.Property<DateTime>("FlowDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("FlowDate");

                    b.Property<DateTime?>("ReconciledDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("ReconciledDate");

                    b.Property<bool>("Reversed")
                        .HasColumnType("boolean")
                        .HasColumnName("Reversed");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("TransactionId");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BankTransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Statement", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccrualPeriodDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("AccrualPeriodDate");

                    b.Property<DateTime>("CashFlowDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("CashFlowDate");

                    b.Property<int>("ClassificationId")
                        .HasColumnType("integer")
                        .HasColumnName("ClassificationId");

                    b.Property<int>("CostCenterId")
                        .HasColumnType("integer")
                        .HasColumnName("CostCenterId");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("CurrencyId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Discount");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("DueDate");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("GroupId");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("IssueDate");

                    b.Property<decimal>("LateFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("LateFee");

                    b.Property<string>("Observation")
                        .HasColumnType("text")
                        .HasColumnName("Observation");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("Status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalPaid");

                    b.Property<TransactionType>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("Type");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("GroupId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Finan.Domain.Entities.Account", b =>
                {
                    b.HasOne("Finan.Domain.Entities.Bank", "Bank")
                        .WithMany("Accounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Finan.Domain.Entities.BankTransaction", b =>
                {
                    b.HasOne("Finan.Domain.Entities.Classification", "Classification")
                        .WithMany("BankTransactions")
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany("BankTransactions")
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.Group", "Group")
                        .WithMany("BankTransactions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classification");

                    b.Navigation("CostCenter");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Classification", b =>
                {
                    b.HasOne("Finan.Domain.Entities.Group", "Group")
                        .WithMany("Classifications")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Statement", b =>
                {
                    b.HasOne("Finan.Domain.Entities.Account", "Account")
                        .WithMany("Statements")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.BankTransaction", "BankTransaction")
                        .WithMany("Statements")
                        .HasForeignKey("BankTransactionId");

                    b.HasOne("Finan.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Statements")
                        .HasForeignKey("TransactionId");

                    b.Navigation("Account");

                    b.Navigation("BankTransaction");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Finan.Domain.Entities.Classification", "Classification")
                        .WithMany("Transactions")
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany("Transactions")
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.Currency", "Currency")
                        .WithMany("Transactions")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finan.Domain.Entities.Group", "Group")
                        .WithMany("Transactions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classification");

                    b.Navigation("CostCenter");

                    b.Navigation("Currency");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Account", b =>
                {
                    b.Navigation("Statements");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Bank", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Finan.Domain.Entities.BankTransaction", b =>
                {
                    b.Navigation("Statements");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Classification", b =>
                {
                    b.Navigation("BankTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finan.Domain.Entities.CostCenter", b =>
                {
                    b.Navigation("BankTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Currency", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Group", b =>
                {
                    b.Navigation("BankTransactions");

                    b.Navigation("Classifications");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finan.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Statements");
                });
#pragma warning restore 612, 618
        }
    }
}
